version: '2'
services:
  app.develop:
    container_name: app.develop
    build:
      context: .
    image: develop
    links:
      - app.db
      - app.redis
      - app.mail
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
    volumes:
     - ./backend:/var/www
    ports:
     - "80:80"

  app.db:
    container_name: app.db
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_USERNAME: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app

  app.redis:
    container_name: app.redis
    image: redis
    links:
      - app.db
    ports:
      - 6379:6379

  app.mail:
    container_name: app.mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
